export  const CARD_ADD_ITEM = 'CARD_ADD_ITEM';
export const CARD_REMOVE_ITEM = 'CARD_REMOVE_ITEM';
export const  CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';
export const  CART_PAYEMENT_METHOD = 'CART_PAYEMENT_METHOD';
