export const PRODUCT_LISTREQUEST = 'PRODUCT_LISTREQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAILED = 'PRODUCT_LIST_FAILED';


export const PRODUCT_Details_REQUEST = 'PRODUCT_Details_REQUEST';
export const PRODUCT_Details_SUCCESS = 'PRODUCT_Details_SUCCESS';
export const PRODUCT_Details_FAILED = 'PRODUCT_Details_FAILED';


export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAILED = 'PRODUCT_DELETE_FAILED';


export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST';
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS';
export const PRODUCT_CREATE_FAILED = 'PRODUCT_CREATE_FAILED';
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET';

