export const PRODUCT_LISTREQUEST = 'PRODUCT_LISTREQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAILED = 'PRODUCT_LIST_FAILED';


export const PRODUCT_Details_REQUEST = 'PRODUCT_Details_REQUEST';
export const PRODUCT_Details_SUCCESS = 'PRODUCT_Details_SUCCESS';
export const PRODUCT_Details_FAILED = 'PRODUCT_Details_FAILED';


export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAILED = 'PRODUCT_DELETE_FAILED';


export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST';
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS';
export const PRODUCT_CREATE_FAILED = 'PRODUCT_CREATE_FAILED';
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET';


export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST';
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAILED = 'PRODUCT_UPDATE_FAILED';
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET';


export const PRODUCT_CREATE_REVIEWS_REQUEST = 'PRODUCT_CREATE_REVIEWS_REQUEST';
export const PRODUCT_CREATE_REVIEWS_SUCCESS = 'PRODUCT_CREATE_REVIEWS_SUCCESS';
export const PRODUCT_CREATE_REVIEWS_FAILED = 'PRODUCT_CREATE_REVIEWS_FAILED';
export const PRODUCT_CREATE_REVIEWS_RESET= 'PRODUCT_CREATE_REVIEWS_RESET';

export const PRODUCT_TOP_REQUEST = 'PRODUCT_TOP_REQUEST';
export const PRODUCT_TOP_SUCCESS = 'PRODUCT_TOP_SUCCESS';
export const PRODUCT_TOP_FAILED = 'PRODUCT_TOP_FAILED';